# Generated by Django 5.2.4 on 2025-07-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_category_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
